# Generated by Django 6.0.1 on 2026-02-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goodincomes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idStock', models.IntegerField(default=0)),
                ('nameStock', models.CharField(max_length=500)),
                ('idGood', models.IntegerField(default=0)),
                ('nameGood', models.CharField(max_length=500)),
                ('qty', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Goodmoves',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameStockFrom', models.CharField(max_length=500)),
                ('nameStockTowhere', models.CharField(max_length=500)),
                ('nameGood', models.CharField(max_length=500)),
                ('qty', models.IntegerField(default=0)),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Goodrests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameStock', models.CharField(max_length=500)),
                ('nameGood', models.CharField(max_length=500)),
                ('qty', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameGood', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nameStock', models.CharField(max_length=500)),
            ],
        ),
    ]
